spring:
  datasource:
    url: jdbc:mysql://localhost:3306/library
    username: app
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  flyway:
    enabled: true
    locations: classpath:db/migration
    schemas: library
    default-schema: library
    baseline-on-migrate: false   # (스키마에 테이블이 있는데 히스토리만 없는 경우 true로 둘 수 있음)

logging:
  level:
    root: INFO
    com.zaxxer.hikari: TRACE
    org.flywaydb: DEBUG

